ontimedata = {
    patients: [{
            id: '1',
            FName: 'Aichael',
            middleInitial: 'ami',
            LName: 'Qin1',
            nameSuffix: 'mq',
            dateOfBirth: '05/12/1984',
            gender: 'F',
            phone: '1304008000',
            addressDataId: {
                address1: 'Avenue #1',
                address2: 'Newyork',
                city: 'NYC',
                state: 'NY',
                zipcode: '300400'
            },
            staffingCordinatorId: '1',
            nurseCaseManagerId: '1',
            careCordinatorId: '1',
            locationLatitude: '40.7127837',
            locationLongitude: '-74.00594',
            insuranceProviderId: '1',
            planName: 'Premium',
            policyNumber: '10001',
            mrnNumber: '20001',
            isSubscriber: true,
            authorization: 'auth',
            careCordinator: 'Bruce Lee',
            careCordinatorContact: '(130) 400-8000',
            insuranceProvider: 'National Insurance.',
            insuranceId: '1223343',
            subscriberInfo: {
                FName: 'Aichael',
                middleInitial: 'ami',
                LName: 'Qin1',
                nameSuffix: 'mq',
                dateOfBirth: '05/12/1984',
                gender: 'F',
            }
        }, {
            id: '2',
            FName: 'Bichael',
            middleInitial: 'bmi',
            LName: 'Qin',
            nameSuffix: 'mq',
            dateOfBirth: '05/12/1984',
            gender: 'M',
            phone: '0304008001',
            staffingCordinatorId: '1',
            nurseCaseManagerId: '1',
            careCordinatorId: '1',
            addressDataId: {
                address1: 'Avenue #1',
                address2: 'Newyork',
                city: 'NYC',
                state: 'NY',
                zipcode: '300400'
            },
            locationLatitude: '19.075',
            locationLongitude: '72.877',
            insuranceProviderId: '1',
            planName: 'Premium',
            policyNumber: '10001',
            mrnNumber: '20001',
            isSubscriber: true,
            authorization: 'auth',
            careCordinator: 'Bruce Lee',
            careCordinatorContact: '(130) 400-8000',
            insuranceProvider: 'National Insurance.',
            insuranceId: 'National Insurance.',
            subscriberInfo: {
                FName: 'Aichael',
                middleInitial: 'ami',
                LName: 'Qin1',
                nameSuffix: 'mq',
                dateOfBirth: '05/12/1984',
                gender: 'F',
            }
        }, {
            id: '3',
            FName: 'Cichael',
            middleInitial: 'cmi',
            LName: 'Qin',
            nameSuffix: 'mq',
            dateOfBirth: '05/12/1984',
            gender: 'M',
            phone: '2304008002',
            addressDataId: {
                address1: 'Avenue #1',
                address2: 'Newyork',
                city: 'NYC',
                state: 'NY',
                zipcode: '300400'
            },
            staffingCordinatorId: '1',
            nurseCaseManagerId: '1',
            careCordinatorId: '1',
            locationLatitude: '100',
            locationLongitude: '1000',
            insuranceProviderId: '1',
            planName: 'Premium',
            policyNumber: '10001',
            mrnNumber: '20001',
            isSubscriber: false,
            authorization: 'auth',
            careCordinator: 'Bruce Lee',
            careCordinatorContact: '(130) 400-8000',
            insuranceProvider: 'National Insurance.',
            insuranceId: 'National Insurance.',
            subscriberInfo: {
                FName: 'Aichael',
                middleInitial: 'ami',
                LName: 'Qin1',
                nameSuffix: 'mq',
                dateOfBirth: '05/12/1984',
                gender: 'F',
            }
        }],
    employees: [{"id": 1,
            "fName": "Hamma",
            wages: "S",
            taxStatus: "1099",
            "lName": "Kureshi",
            "middleInitial": 'ami',
            "dateOfBirth": '05/12/1984',
            "socialSecurity": "3423783452",
            "phone": "0216596425",
            "email": "mohamed.abderrahmen@gmail.com",
            "city": "Tunis",
            "state": "NV",
            "address1": "209-NY Avenue",
            "zipcode": "2036",
            "role": "Administrator",
            "position": "Admin",
            "status": "OK",
            "timeSheetList": []
        }, {"id": 2,
            wages: "H",
            taxStatus: "1099",
            "fName": "Namma",
            "lName": "Abderran",
            middleInitial: 'cmi',
            dateOfBirth: '05/12/1984',
            "socialSecurity": "3423783452",
            "phone": "0216596425",
            "email": "mohamed.abderrahmen@gmail.com",
            "city": "Tunis",
            "state": "NV",
            "address1": "203-NY Avenue",
            "address2": "Street No-5",
            "zipcode": "2036",
            "role": "Administrator",
            "position": "Personal Care",
            "status": "OK",
            "timeSheetList": []
        }, {"id": 3,
            wages: "H",
            taxStatus: "W-2",
            "fName": "Karry",
            "lName": "Neil",
            middleInitial: 'bmi',
            dateOfBirth: '05/12/1984',
            "socialSecurity": "3423783452",
            "phone": "0216596425",
            "email": "mohamed.abderrahmen@gmail.com",
            "city": "Tunis",
            "state": "NV",
            "address1": "23-NYC Planet",
            "address2": "Street No-7",
            "zipcode": "2036",
            "role": "Staff",
            "position": "Admin",
            "status": "OK",
            "timeSheetList": []
        }],
    dailyAttendance: [
        {
            "employeeId": {
                "FName": "Namma",
                "employeeCareRatesList": [],
                "fName": "Namma",
                "id": 1,
                "lName": "Abderran",
                "orgCode": ""
            },
            "id": 1,
            "orgCode": "elance",
            "patientId": {
                "FName": "Sessi",
                "LName": "Sessi",
                "exist": false,
                "id": 1,
                "middleInitial": "SEs",
                "orgCode": "",
                "patientAddress": {
                    "address1": "Tunisia",
                    "address2": "Tunis",
                    "city": "Tunis",
                    "id": 1,
                    "state": "Benna"
                },
                "patientCareTypeCollection": [],
                "subscriberInfo": []
            },
            "punchInTime": "2015-05-13T00:00:01+01:00",
            "punchOutTime": "2008-01-01T00:00:01+01:00"
        },
        {
            "employeeId": {
                "FName": "Karry",
                "employeeCareRatesList": [],
                "fName": "Karry",
                "id": 1,
                "lName": "Neil",
                "orgCode": ""
            },
            "id": 1,
            "orgCode": "elance",
            "patientId": {
                "FName": "Sessi",
                "LName": "Sessi",
                "exist": false,
                "id": 1,
                "middleInitial": "SEs",
                "orgCode": "",
                "patientAddress": {
                    "address1": "Tunisia",
                    "address2": "Tunis",
                    "city": "Tunis",
                    "id": 1,
                    "state": "Benna"
                },
                "patientCareTypeCollection": [],
                "subscriberInfo": []
            },
            "punchInTime": "2015-05-13T00:00:01+01:00",
            "punchOutTime": "2008-01-01T00:00:01+01:00"
        }
    ],
    employeeTimesheet: [
        {
            "employeeId": {
                "FName": "Jack",
                "employeeCareRatesList": [],
                "fName": "Jack",
                "id": 1,
                "lName": "Straw",
                "orgCode": ""
            },
            "id": 1,
            "orgCode": "elance",
            "patientId": {"FName": "Sessi", "LName": "Sessi", "exist": false, "id": 1, "middleInitial": "SEs", "orgCode": "", "patientAddress": {"address1": "Tunisia", "address2": "Tunis", "city": "Tunis", "id": 1, "state": "Benna"}, "patientCareTypeCollection": [],
                "subscriberInfo": []
            },
            "punchInTime": "2015-05-01T09:00:01+01:00",
            "punchOutTime": "2015-05-01T10:03:01+01:00"
        },
        {
            "employeeId": {
                "FName": "Jack",
                "employeeCareRatesList": [],
                "fName": "Jack",
                "id": 1,
                "lName": "Straw",
                "orgCode": ""
            },
            "id": 1,
            "orgCode": "elance",
            "patientId": {"FName": "Sessi", "LName": "Sessi", "exist": false, "id": 1, "middleInitial": "SEs", "orgCode": "", "patientAddress": {"address1": "Tunisia", "address2": "Tunis", "city": "Tunis", "id": 1, "state": "Benna"}, "patientCareTypeCollection": [],
                "subscriberInfo": []
            },
            "punchInTime": "2015-04-15T09:00:01+01:00",
            "punchOutTime": "2015-04-15T10:03:01+01:00"
        }
    ],
    insuranceProviders: [
        {"id": 1,
            "insuranceName": "Insurer 1",
            "billingID": "1234",
            "mdol": "MD Online",
            "planType": "1",
            "contactName": "Contact 1",
            "contactNumber": "124567890",
            "contactAddress": "Address 1",
            "contactEmail": "h@f",
            "contractStartDate": "2015-06-01T18:30:00.000Z",
            "contractEndDate": "2015-06-03T18:29:59.999Z",
//            "careTypes": ["1"]
        }
    ]
};

ontimetest = {
    'weburl': 'api/',
    'defaultState': 'login',
    'patients': ontimedata.patients,
    'employees': ontimedata.employees,
    'dailyAttendance': ontimedata.dailyAttendance,
    'employeeTimesheet': ontimedata.employeeTimesheet,
    'insuranceProviders': ontimedata.insuranceProviders,
//    'getPatients': function($scope, $rootScope, $http) {
//        $scope.patients = ontimedata.patients;
//    },
};
